const laptopData = [
  {
    id: 96,
    img: asus1,
    title: "asus vivobook 11",
    price: 52999,
    company: "asus",
    category: "notebook",
    type: "laptop",
    display: "oled",
    processor: "intel",
    ram: "8 GB",
    ssd: "256 GB",
    hdd: "512 GB",
    camera: "48mp",
    description:
      "This is the description for Asus Vivobook 11. It comes with a vibrant OLED display, Intel processor, 8 GB RAM, and ample storage options.",
  },
  {
    id: 97,
    img: asus2,
    title: "asus chromebook",
    price: 53999,
    company: "asus",
    category: "chromebook",
    type: "laptop",
    display: "amoled",
    processor: "intel",
    ram: "16 GB",
    ssd: "512 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for Asus Chromebook. It features an AMOLED display, Intel processor, 16 GB RAM, and spacious storage options.",
  },
  {
    id: 98,
    img: asus3,
    title: "asus notebook 12",
    price: 54999,
    company: "asus",
    category: "notebook",
    type: "Laptop",
    display: "superamoled",
    processor: "intel",
    ram: "32 GB",
    ssd: "512 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for Asus Notebook 12. It features a Super AMOLED display, Intel processor, 32 GB RAM, and ample storage options.",
  },
  {
    id: 99,
    img: asus4,
    title: "asus notebook 15",
    price: 58999,
    company: "asus",
    category: "notebook",
    type: "Laptop",
    display: "superamoled",
    processor: "intel",
    ram: "8 GB",
    ssd: "256 GB",
    hdd: "512 GB",
    camera: "48mp",
    description:
      "This is the description for Asus Notebook 15. It features a Super AMOLED display, Intel processor, 8 GB RAM, and ample storage options.",
  },
  {
    id: 100,
    img: asus5,
    title: "asus notebook 14",
    price: 55999,
    company: "asus",
    category: "notebook",
    type: "Laptop",
    display: "superamoled",
    processor: "intel",
    ram: "8 GB",
    ssd: "256 GB",
    hdd: "512 GB",
    camera: "48mp",
    description:
      "This is the description for Asus Notebook 14. It features a Super AMOLED display, Intel processor, 8 GB RAM, and ample storage options.",
  },
  {
    id: 101,
    img: asus6,
    title: "asus notebook 13",
    price: 56999,
    company: "asus",
    category: "notebook",
    type: "Laptop",
    display: "superamoled",
    processor: "ryzen",
    ram: "16 GB",
    ssd: "512 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for Asus Notebook 13. It features a Super AMOLED display, Ryzen processor, 16 GB RAM, and spacious storage options.",
  },
  {
    id: 102,
    img: asus7,
    title: "asus chromebook",
    price: 57999,
    company: "asus",
    category: "chromebook",
    type: "Laptop",
    display: "amoled",
    processor: "ryzen",
    ram: "16 GB",
    ssd: "512 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for Asus Chromebook. It features an AMOLED display, Ryzen processor, 16 GB RAM, and spacious storage options.",
  },
  {
    id: 103,
    img: asus8,
    title: "asus chromebook",
    price: 58999,
    company: "asus",
    category: "chromebook",
    type: "Laptop",
    display: "amoled",
    processor: "ryzen",
    ram: "32 GB",
    ssd: "256 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for Asus Chromebook. It features an AMOLED display, Ryzen processor, 32 GB RAM, and spacious storage options.",
  },
  {
    id: 104,
    img: asus9,
    title: "asus chromebook",
    price: 59999,
    company: "asus",
    category: "chromebook",
    type: "Laptop",
    display: "oled",
    processor: "ryzen",
    ram: "32 GB",
    ssd: "256 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for Asus Chromebook. It features an OLED display, Ryzen processor, 32 GB RAM, and spacious storage options.",
  },
  {
    id: 105,
    img: asus10,
    title: "asus chromebook",
    price: 62999,
    company: "asus",
    category: "chromebook",
    type: "Laptop",
    display: "oled",
    processor: "ryzen",
    ram: "32 GB",
    ssd: "256 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for Asus Chromebook. It features an OLED display, Ryzen processor, 32 GB RAM, and spacious storage options.",
  },

  {
    id: 106,
    img: dell1,
    title: "dell vivobook 11",
    price: 52999,
    company: "dell",
    category: "notebook",
    type: "laptop",
    display: "oled",
    processor: "intel",
    ram: "8 GB",
    ssd: "256 GB",
    hdd: "512 GB",
    camera: "48mp",
    description:
      "This is the description for dell Vivobook 11. It comes with a vibrant OLED display, Intel processor, 8 GB RAM, and ample storage options.",
  },
  {
    id: 107,
    img: dell2,
    title: "dell chromebook",
    price: 53999,
    company: "dell",
    category: "chromebook",
    type: "laptop",
    display: "amoled",
    processor: "intel",
    ram: "16 GB",
    ssd: "512 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for dell Chromebook. It features an AMOLED display, Intel processor, 16 GB RAM, and spacious storage options.",
  },
  {
    id: 108,
    img: dell3,
    title: "dell notebook 12",
    price: 54999,
    company: "dell",
    category: "notebook",
    type: "Laptop",
    display: "superamoled",
    processor: "intel",
    ram: "32 GB",
    ssd: "512 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for dell Notebook 12. It features a Super AMOLED display, Intel processor, 32 GB RAM, and ample storage options.",
  },
  {
    id: 109,
    img: dell4,
    title: "dell vivobook 11",
    price: 52999,
    company: "dell",
    category: "notebook",
    type: "laptop",
    display: "oled",
    processor: "intel",
    ram: "8 GB",
    ssd: "256 GB",
    hdd: "512 GB",
    camera: "48mp",
    description:
      "This is the description for dell Vivobook 11. It comes with a vibrant OLED display, Intel processor, 8 GB RAM, and ample storage options.",
  },
  {
    id: 110,
    img: dell5,
    title: "dell chromebook",
    price: 53999,
    company: "dell",
    category: "chromebook",
    type: "laptop",
    display: "amoled",
    processor: "intel",
    ram: "16 GB",
    ssd: "512 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for dell Chromebook. It features an AMOLED display, Intel processor, 16 GB RAM, and spacious storage options.",
  },
  {
    id: 111,
    img: dell6,
    title: "dell notebook 12",
    price: 54999,
    company: "dell",
    category: "notebook",
    type: "Laptop",
    display: "superamoled",
    processor: "intel",
    ram: "32 GB",
    ssd: "512 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for dell Notebook 12. It features a Super AMOLED display, Intel processor, 32 GB RAM, and ample storage options.",
  },
  {
    id: 112,
    img: dell7,
    title: "dell vivobook 11",
    price: 52999,
    company: "dell",
    category: "notebook",
    type: "laptop",
    display: "oled",
    processor: "intel",
    ram: "8 GB",
    ssd: "256 GB",
    hdd: "512 GB",
    camera: "48mp",
    description:
      "This is the description for dell Vivobook 11. It comes with a vibrant OLED display, Intel processor, 8 GB RAM, and ample storage options.",
  },
  {
    id: 113,
    img: dell8,
    title: "dell chromebook",
    price: 53999,
    company: "dell",
    category: "chromebook",
    type: "laptop",
    display: "amoled",
    processor: "intel",
    ram: "16 GB",
    ssd: "512 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for dell Chromebook. It features an AMOLED display, Intel processor, 16 GB RAM, and spacious storage options.",
  },
  {
    id: 114,
    img: dell9,
    title: "dell notebook 12",
    price: 54999,
    company: "dell",
    category: "notebook",
    type: "Laptop",
    display: "superamoled",
    processor: "intel",
    ram: "32 GB",
    ssd: "512 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for dell Notebook 12. It features a Super AMOLED display, Intel processor, 32 GB RAM, and ample storage options.",
  },
  {
    id: 115,
    img: dell10,
    title: "dell notebook 12",
    price: 54999,
    company: "dell",
    category: "notebook",
    type: "Laptop",
    display: "superamoled",
    processor: "intel",
    ram: "32 GB",
    ssd: "512 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for dell Notebook 12. It features a Super AMOLED display, Intel processor, 32 GB RAM, and ample storage options.",
  },

  {
    id: 116,
    img: hp1,
    title: "hp vivobook 11",
    price: 52999,
    company: "hp",
    category: "notebook",
    type: "laptop",
    display: "oled",
    processor: "intel",
    ram: "8 GB",
    ssd: "256 GB",
    hdd: "512 GB",
    camera: "48mp",
    description:
      "This is the description for hp Vivobook 11. It comes with a vibrant OLED display, Intel processor, 8 GB RAM, and ample storage options.",
  },
  {
    id: 117,
    img: hp2,
    title: "hp chromebook",
    price: 53999,
    company: "hp",
    category: "chromebook",
    type: "laptop",
    display: "amoled",
    processor: "intel",
    ram: "16 GB",
    ssd: "512 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for hp Chromebook. It features an AMOLED display, Intel processor, 16 GB RAM, and spacious storage options.",
  },
  {
    id: 118,
    img: hp3,
    title: "hp notebook 12",
    price: 54999,
    company: "hp",
    category: "notebook",
    type: "Laptop",
    display: "superamoled",
    processor: "intel",
    ram: "32 GB",
    ssd: "512 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for hp Notebook 12. It features a Super AMOLED display, Intel processor, 32 GB RAM, and ample storage options.",
  },
  {
    id: 119,
    img: hp4,
    title: "hp vivobook 11",
    price: 52999,
    company: "hp",
    category: "notebook",
    type: "laptop",
    display: "oled",
    processor: "intel",
    ram: "8 GB",
    ssd: "256 GB",
    hdd: "512 GB",
    camera: "48mp",
    description:
      "This is the description for hp Vivobook 11. It comes with a vibrant OLED display, Intel processor, 8 GB RAM, and ample storage options.",
  },
  {
    id: 120,
    img: hp5,
    title: "hp chromebook",
    price: 53999,
    company: "hp",
    category: "chromebook",
    type: "laptop",
    display: "amoled",
    processor: "intel",
    ram: "16 GB",
    ssd: "512 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for hp Chromebook. It features an AMOLED display, Intel processor, 16 GB RAM, and spacious storage options.",
  },
  {
    id: 121,
    img: hp6,
    title: "hp notebook 12",
    price: 54999,
    company: "hp",
    category: "notebook",
    type: "Laptop",
    display: "superamoled",
    processor: "intel",
    ram: "32 GB",
    ssd: "512 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for hp Notebook 12. It features a Super AMOLED display, Intel processor, 32 GB RAM, and ample storage options.",
  },
  {
    id: 122,
    img: hp7,
    title: "hp vivobook 11",
    price: 52999,
    company: "hp",
    category: "notebook",
    type: "laptop",
    display: "oled",
    processor: "intel",
    ram: "8 GB",
    ssd: "256 GB",
    hdd: "512 GB",
    camera: "48mp",
    description:
      "This is the description for hp Vivobook 11. It comes with a vibrant OLED display, Intel processor, 8 GB RAM, and ample storage options.",
  },
  {
    id: 123,
    img: hp8,
    title: "hp chromebook",
    price: 53999,
    company: "hp",
    category: "chromebook",
    type: "laptop",
    display: "amoled",
    processor: "intel",
    ram: "16 GB",
    ssd: "512 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for hp Chromebook. It features an AMOLED display, Intel processor, 16 GB RAM, and spacious storage options.",
  },
  {
    id: 124,
    img: hp9,
    title: "hp notebook 12",
    price: 54999,
    company: "hp",
    category: "notebook",
    type: "Laptop",
    display: "superamoled",
    processor: "intel",
    ram: "32 GB",
    ssd: "512 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for hp Notebook 12. It features a Super AMOLED display, Intel processor, 32 GB RAM, and ample storage options.",
  },
  {
    id: 125,
    img: hp10,
    title: "hp notebook 12",
    price: 54999,
    company: "hp",
    category: "notebook",
    type: "Laptop",
    display: "superamoled",
    processor: "intel",
    ram: "32 GB",
    ssd: "512 GB",
    hdd: "1 TB",
    camera: "48mp",
    description:
      "This is the description for hp Notebook 12. It features a Super AMOLED display, Intel processor, 32 GB RAM, and ample storage options.",
  },
];
