const mobilesData = [
  {
    id: 1,
    img: iphone1,
    title: "iPhone 13 Pro",
    price: 70000,
    company: "Apple",
    category: "iOS",
    type: "mobiles",
    display: "amoled",
    processor: "Bionic",
    ram: "6 GB",
    storage: "128 GB",
    camera: "64mp",
    description:
      "The iPhone 13 Pro features a stunning Super AMOLED display, powerful A15 Bionic chip, and an advanced triple-camera system for exceptional photography.",
  },
  {
    id: 2,
    img: iphone2,
    title: "iPhone 12",
    price: 60000,
    company: "Apple",
    category: "iOS",
    type: "mobiles",
    display: "oled",
    processor: "Bionic",
    ram: "4 GB",
    storage: "64 GB",
    camera: "64mp",
    description:
      "Experience the brilliance of the iPhone 12 with its vibrant OLED display, A14 Bionic chip, and dual-camera system for stunning photos and videos.",
  },
  {
    id: 3,
    img: iphone3,
    title: "iPhone SE (2020)",
    price: 35000,
    company: "Apple",
    category: "iOS",
    type: "mobiles",
    display: "oled",
    processor: "Bionic",
    ram: "3 GB",
    storage: "128 GB",
    camera: "100mp",
    description:
      "The iPhone SE (2020) combines the power of the A13 Bionic chip with a compact design, making it a perfect choice for those who prefer a smaller form factor.",
  },
  {
    id: 4,
    img: iphone4,
    title: "iPhone 11 Pro",
    price: 80000,
    company: "Apple",
    category: "iOS",
    type: "mobiles",
    display: "superamoled",
    processor: "Bionic",
    ram: "4 GB",
    storage: "256 GB",
    camera: "200mp",
    description:
      "Immerse yourself in the vivid Super Retina XDR display of the iPhone 11 Pro, coupled with the power of the A13 Bionic chip and a versatile triple-camera system.",
  },
  {
    id: 5,
    img: iphone5,
    title: "iPhone XR",
    price: 45000,
    company: "Apple",
    category: "iOS",
    type: "mobiles",
    display: "superamoled",
    processor: "A12 Bionic",
    ram: "3 GB",
    storage: "64 GB",
    camera: "200mp",
    description:
      "The iPhone XR features a brilliant Liquid Retina display, A12 Bionic chip, and a single-lens camera, delivering a premium iPhone experience at a more affordable price.",
  },
  {
    id: 6,
    img: oneplus1,
    title: "OnePlus 9 Pro",
    price: 69999,
    company: "OnePlus",
    category: "Android",
    type: "mobiles",
    display: "amoled",
    processor: "Snapdragon",
    ram: "8 GB",
    storage: "128 GB",
    camera: "200mp",
    description:
      "The OnePlus 9 Pro boasts a Fluid AMOLED display, Snapdragon 888 processor, and a versatile quad-camera setup for stunning photography and performance.",
  },
  {
    id: 7,
    img: oneplus2,
    title: "OnePlus 8T",
    price: 42999,
    company: "OnePlus",
    category: "Android",
    type: "mobiles",
    display: "oled",
    processor: "Snapdragon 865",
    ram: "12 GB",
    storage: "256 GB",
    camera: "64mp",
    description:
      "Experience smooth performance and vibrant visuals with the OnePlus 8T, featuring a Fluid AMOLED display, Snapdragon 865 chipset, and a powerful quad-camera system.",
  },
  {
    id: 8,
    img: oneplus3,
    title: "OnePlus Nord 2",
    price: 29999,
    company: "OnePlus",
    category: "Android",
    type: "mobiles",
    display: "superamoled",
    processor: "MediaTek",
    ram: "8 GB",
    storage: "128 GB",
    camera: "100mp",
    description:
      "The OnePlus Nord 2 features a vibrant AMOLED display, MediaTek Dimensity 1200 processor, and a triple-camera system for a premium mid-range smartphone experience.",
  },
  {
    id: 9,
    img: oneplus4,
    title: "OnePlus 7 Pro",
    price: 52999,
    company: "OnePlus",
    category: "Android",
    type: "mobiles",
    display: "oled",
    processor: "Snapdragon",
    ram: "8 GB",
    storage: "256 GB",
    camera: "48mp",
    description:
      "Immerse yourself in the stunning Fluid AMOLED display of the OnePlus 7 Pro, powered by the Snapdragon 855 chipset and equipped with a versatile triple-camera setup.",
  },
  {
    id: 10,
    img: oneplus5,
    title: "OnePlus 8",
    price: 39999,
    company: "OnePlus",
    category: "Android",
    type: "mobiles",
    display: "superamoled",
    processor: "Snapdragon",
    ram: "12 GB",
    storage: "128 GB",
    camera: "T64mp",
    description:
      "The OnePlus 8 features a Fluid AMOLED display, Snapdragon 865 processor, and a versatile triple-camera system, delivering a flagship experience at a competitive price.",
  },
  {
    id: 11,
    img: oneplus6,
    title: "OnePlus 9",
    price: 54999,
    company: "OnePlus",
    category: "Android",
    type: "mobiles",
    display: "oled",
    processor: "MediaTek",
    ram: "8 GB",
    storage: "128 GB",
    camera: "200mp",
    description:
      "Experience top-tier performance and photography with the OnePlus 9, featuring a Fluid AMOLED display, Snapdragon 888 chipset, and a triple-camera setup.",
  },
  {
    id: 12,
    img: oneplus7,
    title: "OnePlus Nord",
    price: 27999,
    company: "OnePlus",
    category: "Android",
    type: "mobiles",
    display: "amoled",
    processor: "Snapdragon",
    ram: "6 GB",
    storage: "64 GB",
    camera: "48mp",
    description:
      "The OnePlus Nord offers a smooth AMOLED display, Snapdragon 765G processor, and a versatile quad-camera system, making it an excellent choice for mid-range enthusiasts.",
  },
  {
    id: 13,
    img: oneplus8,
    title: "OnePlus 7T",
    price: 34999,
    company: "OnePlus",
    category: "Android",
    type: "mobiles",
    display: "oled",
    processor: "Snapdragon",
    ram: "8 GB",
    storage: "128 GB",
    camera: "64mp",
    description:
      "Upgrade to flagship performance with the OnePlus 7T, featuring a Fluid AMOLED display, Snapdragon 855+ chipset, and a powerful triple-camera system.",
  },
  {
    id: 14,
    img: oneplus9,
    title: "OnePlus Nord CE 5G",
    price: 22999,
    company: "OnePlus",
    category: "Android",
    type: "mobiles",
    display: "amoled",
    processor: "MeadiaTek",
    ram: "6 GB",
    storage: "128 GB",
    camera: "200mp",
    description:
      "The OnePlus Nord CE 5G offers a Fluid AMOLED display, Snapdragon 750G processor, and a triple-camera system for a compelling 5G-enabled mid-range experience.",
  },
  {
    id: 15,
    img: oneplus10,
    title: "OnePlus 6T",
    price: 32999,
    company: "OnePlus",
    category: "Android",
    type: "mobiles",
    display: "superamoled",
    processor: "Snapdragon",
    ram: "8 GB",
    storage: "128 GB",
    camera: "100mp",
    description:
      "The OnePlus 6T features a vibrant AMOLED display, Snapdragon 845 processor, and a dual-camera system for a flagship-like experience at an affordable price.",
  },
  {
    id: 16,
    img: oppo1,
    title: "Oppo Find X3 Pro",
    price: 74999,
    company: "Oppo",
    category: "Android",
    type: "mobiles",
    display: "amoled",
    processor: "Snapdragon",
    ram: "12 GB",
    storage: "256 GB",
    camera: "48mp",
    description:
      "Explore the excellence of the Oppo Find X3 Pro with its vibrant AMOLED display, Snapdragon 888 processor, and a cutting-edge quad-camera system for exceptional photography and performance.",
  },
  {
    id: 17,
    img: oppo2,
    title: "Oppo Reno6 Pro+",
    price: 54999,
    company: "Oppo",
    category: "Android",
    type: "mobiles",
    display: "superamoled",
    processor: "MediaTek",
    ram: "8 GB",
    storage: "128 GB",
    camera: "64mp",
    description:
      "Experience the Oppo Reno6 Pro+ with its stunning AMOLED display, Dimensity 1200 processor, and a powerful quad-camera setup for impressive photography and smooth performance.",
  },
  {
    id: 18,
    img: oppo3,
    title: "Oppo F19 Pro+",
    price: 27999,
    company: "Oppo",
    category: "Android",
    type: "mobiles",
    display: "oled",
    processor: "MediaTek",
    ram: "8 GB",
    storage: "128 GB",
    camera: "48mp",
    description:
      "The Oppo F19 Pro+ features a Super AMOLED display, MediaTek Dimensity 800U processor, and a versatile quad-camera system, delivering a compelling mid-range smartphone experience.",
  },
  {
    id: 19,
    img: oppo4,
    title: "Oppo A74 5G",
    price: 19999,
    company: "Oppo",
    category: "Android",
    type: "mobiles",
    display: "amoled",
    processor: "Snapdragon",
    ram: "6 GB",
    storage: "128 GB",
    camera: "48mp",
    description:
      "Enjoy the Oppo A74 5G with its smooth 90Hz IPS LCD display, Snapdragon 480 processor, and a triple-camera system, providing a great 5G-enabled experience at an affordable price.",
  },
  {
    id: 20,
    img: oppo5,
    title: "Oppo Reno5 Pro",
    price: 35999,
    company: "Oppo",
    category: "Android",
    type: "mobiles",
    display: "superamoled",
    processor: "MediaTek",
    ram: "8 GB",
    storage: "128 GB",
    camera: "64mp",
    description:
      "Immerse yourself in the Oppo Reno5 Pro's Super AMOLED display, powered by the Dimensity 1000+ processor and featuring a quad-camera system for impressive photography.",
  },
  {
    id: 21,
    img: oppo6,
    title: "Oppo A15",
    price: 9999,
    company: "Oppo",
    category: "Android",
    type: "mobiles",
    display: "amoled",
    processor: "Mediatek",
    ram: "3 GB",
    storage: "32 GB",
    camera: "48mp",
    description:
      "The Oppo A15 offers an affordable package with its IPS LCD display, Mediatek Helio P35 processor, and a triple-camera system for everyday photography needs.",
  },
  {
    id: 22,
    img: oppo7,
    title: "Oppo F17 Pro",
    price: 22990,
    company: "Oppo",
    category: "Android",
    type: "mobiles",
    display: "superamoled",
    processor: "Mediatek",
    ram: "8 GB",
    storage: "128 GB",
    camera: "100mp",
    description:
      "The Oppo F17 Pro combines style with performance, featuring a Super AMOLED display, Mediatek Helio P95 processor, and a versatile quad-camera system.",
  },
  {
    id: 23,
    img: oppo8,
    title: "Oppo A53",
    price: 12990,
    company: "Oppo",
    category: "Android",
    type: "mobiles",
    display: "amoled",
    processor: "Snapdragon",
    ram: "4 GB",
    storage: "64 GB",
    camera: "48mp",
    description:
      "The Oppo A53 offers a smooth experience with its 90Hz IPS LCD display, Snapdragon 460 processor, and a triple-camera system for everyday photography needs.",
  },
  {
    id: 24,
    img: oppo9,
    title: "Oppo Reno4 Pro",
    price: 34990,
    company: "Oppo",
    category: "Android",
    type: "mobiles",
    display: "oled",
    processor: "Snapdragon",
    ram: "8 GB",
    storage: "128 GB",
    camera: "200mp",
    description:
      "Experience creativity with the Oppo Reno4 Pro, featuring a Super AMOLED display, Snapdragon 720G processor, and a versatile quad-camera system for stunning visuals.",
  },
  {
    id: 25,
    img: oppo10,
    title: "Oppo A12",
    price: 9999,
    company: "Oppo",
    category: "Android",
    type: "mobiles",
    display: "amoled",
    processor: "Mediatek",
    ram: "3 GB",
    storage: "32 GB",
    camera: "48mp",
    description:
      "The Oppo A12 provides essential features with its IPS LCD display, Mediatek Helio P35 processor, and a dual-camera system for a budget-friendly smartphone experience.",
  },
  {
    id: 26,
    img: vivo1,
    title: "Vivo X60 Pro+",
    price: 69990,
    company: "Vivo",
    category: "Android",
    type: "mobiles",
    display: "oled",
    processor: "Snapdragon",
    ram: "12 GB",
    storage: "256 GB",
    camera: "200mp",
    description:
      "Capture the extraordinary with the Vivo X60 Pro+, featuring a vibrant AMOLED display, Snapdragon 888 processor, and a professional-grade quad-camera system for stunning photography and performance.",
  },
  {
    id: 27,
    img: vivo2,
    title: "Vivo V21e",
    price: 24990,
    company: "Vivo",
    category: "Android",
    type: "mobiles",
    display: "superamoled",
    processor: "MediaTek",
    ram: "8 GB",
    storage: "128 GB",
    camera: "64mp",
    description:
      "Experience sleek design and powerful performance with the Vivo V21e, featuring an AMOLED display, Dimensity 800U processor, and a dual-camera system for impressive photography.",
  },
  {
    id: 28,
    img: vivo3,
    title: "Vivo Y73",
    price: 20990,
    company: "Vivo",
    category: "Android",
    type: "mobiles",
    display: "amoled",
    processor: "MediaTek",
    ram: "8 GB",
    storage: "128 GB",
    camera: "48mp",
    description:
      "Elevate your mobile experience with the Vivo Y73, featuring an AMOLED display, MediaTek Helio G95 processor, and a triple-camera system for versatile photography.",
  },
  {
    id: 29,
    img: vivo4,
    title: "Vivo X50 Pro",
    price: 49990,
    company: "Vivo",
    category: "Android",
    type: "mobiles",
    display: "superamoled",
    processor: "Snapdragon",
    ram: "8 GB",
    storage: "256 GB",
    camera: "100mp",
    description:
      "Unleash creativity with the Vivo X50 Pro, featuring an AMOLED display, Snapdragon 765G processor, and a versatile quad-camera system for exceptional photography and stability.",
  },
  {
    id: 30,
    img: vivo5,
    title: "Vivo S1 Pro",
    price: 19990,
    company: "Vivo",
    category: "Android",
    type: "mobiles",
    display: "amoled",
    processor: "Snapdragon",
    ram: "8 GB",
    storage: "128 GB",
    camera: "48mp",
    description:
      "Step into style and performance with the Vivo S1 Pro, featuring a Super AMOLED display, Snapdragon 665 processor, and a versatile quad-camera system for everyday photography needs.",
  },
  {
    id: 31,
    img: vivo6,
    title: "Vivo Y20G",
    price: 12990,
    company: "Vivo",
    category: "Android",
    type: "mobiles",
    display: "amoled",
    processor: "MediaTek",
    ram: "6 GB",
    storage: "128 GB",
    camera: "48mp",
    description:
      "The Vivo Y20G offers a budget-friendly option with its IPS LCD display, MediaTek Helio G80 processor, and a triple-camera system for essential photography needs.",
  },
  {
    id: 32,
    img: vivo7,
    title: "Vivo V17",
    price: 22990,
    company: "Vivo",
    category: "Android",
    type: "mobiles",
    display: "superamoled",
    processor: "Snapdragon",
    ram: "8 GB",
    storage: "128 GB",
    camera: "100mp",
    description:
      "Experience brilliance with the Vivo V17, featuring a Super AMOLED display, Snapdragon 675 processor, and a versatile quad-camera system for impressive photography.",
  },
  {
    id: 33,
    img: vivo8,
    title: "Vivo Y30",
    price: 14990,
    company: "Vivo",
    category: "Android",
    type: "mobiles",
    display: "amoled",
    processor: "MediaTek",
    ram: "4 GB",
    storage: "128 GB",
    camera: "48mp",
    description:
      "The Vivo Y30 offers a balance of features with its IPS LCD display, MediaTek Helio P35 processor, and a quad-camera system for a budget-friendly smartphone experience.",
  },
  {
    id: 34,
    img: vivo9,
    title: "Vivo V21",
    price: 29990,
    company: "Vivo",
    category: "Android",
    type: "mobiles",
    display: "superamoled",
    processor: "MediaTek",
    ram: "8 GB",
    storage: "128 GB",
    camera: "100mp",
    description:
      "Experience sleek design and advanced features with the Vivo V21, featuring an AMOLED display, Dimensity 800U processor, and a triple-camera system for stunning photography.",
  },
  {
    id: 35,
    img: vivo10,
    title: "Vivo Y12s",
    price: 10990,
    company: "Vivo",
    category: "Android",
    type: "mobiles",
    display: "amoled",
    processor: "MediaTek",
    ram: "3 GB",
    storage: "32 GB",
    camera: "48mp",
    description:
      "The Vivo Y12s offers essential features with its IPS LCD display, MediaTek Helio P35 processor, and a dual-camera system for a budget-friendly smartphone experience.",
  },
];
export default mobilesData;
